apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactmanager-deployment  # Deployment Name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contactmanager  
  template:
    metadata:
      labels:
        app: contactmanager  
    spec:
      containers:
        - name: contactmanager-app
          image: ajusha/contactmanager:latest  # Ensure the latest tag is used
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: contactmanager-service  # Service Name
spec:
  selector:
    app: contactmanager  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
