apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactmanager-deployment  # Deployment Name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contactmanager  
  template:
    metadata:
      labels:
        app: contactmanager  
    spec:
      containers:
        - name: contactmanager-app
          image: ajusha/contactmanager
          ports:
            - containerPort: 8080
